config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users
  resources :users
  resources :api
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable, :validatable
  validates_presence_of :email
  validates_presence_of :username
  validates_presence_of :forename
  validates_presence_of :surname

  def fields_completed
    username.present? && forename.present? && surname.present? && email.present? && profile_image.present?
  end

  def as_json options={}
    {
      forename: self.forename,
      surname: self.surname,
      gender: self.gender,
      created_at: self.created_at
    }
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  before_action :set_user, only: [:show]

  # GET /users/1
  # GET /users/1.json
  def show
    if @user.nil?
      render json: '{"error": "No user with specified ID"}'
    else
      render json: @user
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        @user = nil
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

    protected
      def configure_permitted_parameters
          devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password, :username, :forename, :surname])
      end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    if current_user.fields_completed
      render 'home/index'
    else
      redirect_to edit_user_path(current_user)
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    if current_user.fields_completed
      @users = User.all
    else
      redirect_to edit_user_path(current_user)
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @mode = "show"
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :forename, :surname, :email, :profile_image, :birth_date, :gender, :phone_number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.haml
%h1= "Welcome #{current_user.email}!"
%p
  Go to your
  %a{ href: user_path(current_user)} User page
  \.

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title SimpleWebApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link{href: "https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css", rel: "stylesheet", integrity: "sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh", crossorigin: "anonymous"}
  %body
    .container.wrapper
      - if user_signed_in?
        .pull-right= link_to('Logout', destroy_user_session_path, class: 'btn btn-danger')
      = yield

app/views/users/_form.html.haml
= form_with(model: user, local: true) do |form|
  - if user.errors.any?
    #error_explanation
      %h2
        = pluralize(user.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - user.errors.full_messages.each do |message|
          %li= message
  - if !current_user.fields_completed && @mode!="show"
    %p{style:'color:#ff0000'} You should fill the form.
  .row
    -if form.object.profile_image.present?
      .col-md-12
        %img{src: form.object.profile_image, title: form.object.profile_image}
    .col-md-6
      .field
        = form.label :username
        = form.text_field :username, required: true, autofocus: true, class: 'form-control', readonly: @mode=="show"
      .field
        = form.label :forename
        = form.text_field :forename, required: true, class: 'form-control', readonly: @mode=="show"
      .field
        = form.label :surname
        = form.text_field :surname, required: true, class: 'form-control', readonly: @mode=="show"
      .field
        = form.label :email
        = form.text_field :email, required: true, class: 'form-control', readonly: @mode=="show"
      .field
        = form.label :profile_image
        = form.text_field :profile_image, required: true, class: 'form-control', readonly: @mode=="show"
    .col-md-6
      %small Optional fields:
      .field
        = form.label :birth_date
        = form.date_select :birth_date, {start_year: Date.current.year, end_year: 1920}, {class: 'form-control', disabled: @mode=="show"}
      .field
        = form.label :gender
        = form.select :gender, ['male', 'female'], {}, {class: 'form-control', disabled: @mode=="show"}
      .field
        = form.label :phone_number
        = form.number_field :phone_number, class: 'form-control', readonly: @mode=="show"

  .pull-right
    - if @user.fields_completed
      = link_to 'Back', users_path, class: 'btn btn-secondary'
    -if @mode == "show"
      = link_to 'Edit', edit_user_path(@user), class: 'btn btn-success'
    - else
      = link_to 'Show', @user, class: 'btn btn-secondary'
      = form.submit class: 'btn btn-primary'
  .clear

app/views/users/edit.html.haml
%h1 Editing User
= render 'form', user: @user

app/views/users/index.html.haml
%p#notice= notice
%h1 Users
%table.table.table-bordered
  %thead
    %tr
      %th Username
      %th Forename
      %th Surname
      %th Email
      %th{:colspan => "3"}
  %tbody
    - @users.each do |user|
      %tr
        %td= user.username
        %td= user.forename
        %td= user.surname
        %td= user.email
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New User', new_user_path

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.haml
%p#notice= notice
%h1 User details
= render 'form', user: @user